services:
  app:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DB_URL: jdbc:postgresql://db:5432/cultural_navigator
      DB_USER: cultural_user
      DB_PASSWORD: cultural_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_PORT: 8080
      YANDEX_GEOCODER_API_KEY: ${YANDEX_GEOCODER_API_KEY:-}
    ports:
      - "8080:8080"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cultural_navigator
      POSTGRES_USER: cultural_user
      POSTGRES_PASSWORD: cultural_password
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pg_data:
